uploads = []
outputs = []

[[generated]]
id = "YGtb3PSqa4Rkv8QYaJ8O4"
uri = "file://artifacts/panthers-bite/public/images/wraps-snacks.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Km59JWtvQv2EdFrEDIA89"
uri = "file://artifacts/panthers-bite/public/images/chicken-wings.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Q5itiGwLU3ztrmjUTLlPH"
uri = "file://artifacts/panthers-bite/public/images/combo-meal.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mYZNdXqWA6m2ZwzsixmEw"
uri = "file://artifacts/panthers-bite/public/images/panther-classic-combo.png"
type = "image"
title = "generated_image"

[[generated]]
id = "cAFj4efGGGMALFIOPX-_O"
uri = "file://artifacts/panthers-bite/public/images/spicy-duo-combo.png"
type = "image"
title = "generated_image"
